version: "3"
services:
    db:
        image: mysql:5.7
        container_name: db
        tty: true
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: library
        networks:
            - dev

    api:
        build: php
        container_name: api
        depends_on:
            - db
        ports:
            - "8080:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        networks:
            - dev

networks:
    dev:

volumes:
    db-data: