vich_uploader:
    db_driver: orm

    mappings:
        cover_page:
            uri_prefix: /images/coverPages
            upload_destination: '%kernel.project_dir%/public/images/coverPages'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_update: true
            delete_on_remove: true